spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authentication
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sales-automation
          uri: lb://sales-automation
          predicates:
            - Path=/api/sales-opportunity/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: marketing-automation
          uri: lb://marketing-automation
          predicates:
            - Path=/api/marketing/**
        - id: customer-support
          uri: lb://customer-support
          predicates:
            - Path=/api/support/**
        - id: customer-data-management
          uri: lb://customer-data-management
          predicates:
            - Path=/api/customers/**
        - id: analytics-and-reporting
          uri: lb://analytics-and-reporting
          predicates:
            - Path=/api/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765

secret: wxiTxVJTE263r0L7zFuBcrJInd6fEqeOKDJcFKdzHO4=


