spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sales-automation
          uri: lb://sales-automation
          predicates:
            - Path=/api/sales-opportunity/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: marketing-automation
          uri: lb://marketing-automation
          predicates:
            - Path=/api/marketing/**
        - id: customer-support
          uri: lb://customer-support
          predicates:
            - Path=/api/support/**
        - id: customer-data-management
          uri: lb://customer-data-management
          predicates:
            - Path=/api/customers/**
        - id: analytics-and-reporting
          uri: lb://analytics-and-reporting
          predicates:
            - Path=/api/analytics/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765